package com.team41.boromi.models;

import static com.team41.boromi.constants.CommonConstants.BookStatus;
import static com.team41.boromi.constants.CommonConstants.BookWorkflowStage;

import androidx.annotation.NonNull;
import java.io.Serializable;
import java.util.UUID;

/**
 * A model class storing an information on the book And on which stage the book is currently in
 */
public class Book implements Serializable {

  // SerialVersionUID generated by Android Studio
  private static final long serialVersionUID = -5427418813071062937L;

  private String bookId;
  private String owner;
  private String ISBN;
  private String author;
  private String desc;
  private BookStatus status;
  private BookWorkflowStage workflow;
  private String borrower;

  // TODO
  // I didn't include logic for the requesters/borrowers/img/location
  // To allow the person implementing that logic to decide how they want to do it.
  // You can go through the BookRequests, then only do a read on DB
  // If a user wants more info on a book, or you can store all the requester usernames here..
  // And wipe them on each acceptance.

  /**
   * A no-argument constructor required by firestore to serialize data
   */
  public Book() {}

  /**
   * When UUID not specified, we generate a random UUID to identify the book
   *
   * @param owner
   */
  public Book(String owner) {
    this.bookId = UUID.randomUUID().toString();
    this.owner = owner;
    this.status = BookStatus.AVAILABLE;
    this.workflow = BookWorkflowStage.AVAILABLE;
  }

  public Book(String owner, String bookId) {
    this.bookId = bookId;
    this.owner = owner;
    this.status = BookStatus.AVAILABLE;
    this.workflow = BookWorkflowStage.AVAILABLE;
  }

  // Setters / Getters Start
  @NonNull
  public String getBookId() {
    return bookId;
  }

  @NonNull
  public String getOwner() {
    return owner;
  }

  public String getISBN() {
    return ISBN;
  }

  public void setISBN(String ISBN) {
    this.ISBN = ISBN;
  }

  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public String getDesc() {
    return desc;
  }

  public void setDesc(String desc) {
    this.desc = desc;
  }

  public BookStatus getStatus() {
    return status;
  }

  public void setStatus(BookStatus status) {
    this.status = status;
  }

  public BookWorkflowStage getWorkflow() {
    return workflow;
  }

  public void setWorkflow(BookWorkflowStage workflow) {
    this.workflow = workflow;
  }

  public String getBorrower() {
    return borrower;
  }

  public void setBorrower(String borrower) {
    this.borrower = borrower;
  }
}
