package com.team41.boromi.models;

import static com.team41.boromi.constants.CommonConstants.BookStatus;
import static com.team41.boromi.constants.CommonConstants.BookWorkflowStage;

import androidx.annotation.NonNull;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.UUID;

/**
 * A model class storing an information on the book And on which stage the book is currently in
 */
public class Book implements Serializable {

  // SerialVersionUID generated by Android Studio
  private static final long serialVersionUID = -5427418813071062937L;

  private String owner;
  private String borrower;
  private String title;
  private String author;
  private String ISBN;
  private BookStatus status;
  private BookWorkflowStage workflow;

  private String bookId = UUID.randomUUID().toString();
  private ArrayList<String> requests = new ArrayList<>();

  /**
   * A no-argument constructor required by firestore to serialize data
   */
  public Book() {}

  public Book(String owner, String title, String author, String ISBN) {
    this.owner = owner;
    this.title = title;
    this.author = author;
    this.ISBN = ISBN;

    this.borrower = null;
    this.status = BookStatus.AVAILABLE;
    this.workflow = BookWorkflowStage.AVAILABLE;
  }

  public Book(String owner, String title, String author, String ISBN, BookStatus status) {
    this.owner = owner;
    this.title = title;
    this.author = author;
    this.ISBN = ISBN;
    this.status = status;

    this.borrower = null;
    this.workflow = BookWorkflowStage.AVAILABLE;
  }

  public Book(String owner, String title, String author, String ISBN, BookWorkflowStage workflow) {
    this.owner = owner;
    this.title = title;
    this.author = author;
    this.ISBN = ISBN;
    this.workflow = workflow;

    this.borrower = null;
    this.status = BookStatus.AVAILABLE;
  }

  public Book(
          String owner,
          String title,
          String author,
          String ISBN,
          BookStatus status,
          BookWorkflowStage workflow
  ) {
    this.owner = owner;
    this.title = title;
    this.author = author;
    this.ISBN = ISBN;
    this.status = status;
    this.workflow = workflow;

    this.borrower = null;
  }

  public Book(
          String owner,
          String title,
          String author,
          String ISBN,
          BookStatus status,
          String borrower
  ) {
    this.owner = owner;
    this.borrower = borrower;
    this.title = title;
    this.author = author;
    this.ISBN = ISBN;
    this.status = status;

    this.workflow = BookWorkflowStage.AVAILABLE;
  }

  public Book(
          String owner,
          String title,
          String author,
          String ISBN,
          BookWorkflowStage workflow,
          String borrower
  ) {
    this.owner = owner;
    this.borrower = borrower;
    this.title = title;
    this.author = author;
    this.ISBN = ISBN;
    this.workflow = workflow;

    this.status = BookStatus.AVAILABLE;
  }

  public Book(
          String owner,
          String title,
          String author,
          String ISBN,
          BookStatus status,
          BookWorkflowStage workflow,
          String borrower
  ) {
    this.owner = owner;
    this.borrower = borrower;
    this.title = title;
    this.author = author;
    this.ISBN = ISBN;
    this.workflow = workflow;
    this.status = status;

  }

  // Setters / Getters Start
  public String getBookId() {
    return bookId;
  }

  public String getOwner() {
    return owner;
  }

  public String getBorrower() {
    return borrower;
  }

  public void setBorrower(String borrower) {
    this.borrower = borrower;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public String getISBN() {
    return ISBN;
  }

  public void setISBN(String ISBN) {
    this.ISBN = ISBN;
  }

  public BookStatus getStatus() {
    return status;
  }

  public void setStatus(BookStatus status) {
    this.status = status;
  }

  public BookWorkflowStage getWorkflow() {
    return workflow;
  }

  public void setWorkflow(BookWorkflowStage workflow) {
    this.workflow = workflow;
  }

  public ArrayList<String> getRequests() {
    return requests;
  }

  public void setRequests(ArrayList<String> requests) {
    this.requests = requests;
  }

  /**
   * Add a specified username to the requests
   * @param username
   */
  public void addRequest(String username) {
    this.requests.add(username);
  }

  /**
   * Deletes a specified username from the requests
   * @param username
   */
  public void deleteRequest(String username) {
    this.requests.remove(username);
  }

  /**
   * Clears all requests and sets the borrower
   * @param username The user accepted to borrow the book
   */
  public void acceptRequest(String username) {
    this.requests.clear();
    this.borrower = username;
  }

}
