name: ci-build-check
#  All pushpull requests
on: [push, pull_request]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Building Android Project
        run: |
          chmod +x gradlew
          ./gradlew build
